src/Entity/Lieu.php
<?php

namespace App\Entity;

use App\Repository\LieuRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LieuRepository::class)]
class Lieu
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $Longitude = null;

    #[ORM\Column]
    private ?float $latitude = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $rue = null;

    #[ORM\ManyToOne(targetEntity: Ville::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    // Le camel case pour les variables c'est première lettre en minuscule. $codePostal par exemple.
    private ?Ville $ville = null;

    public function __construct()
    {
    }

    public function getVille(): ?Ville
    {
        return $this->ville;
    }

    public function setVille(?Ville $ville): void
    {
        $this->ville = $ville;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLongitude(): ?float
    {
        return $this->Longitude;
    }

    public function setLongitude(float $Longitude): static
    {
        $this->Longitude = $Longitude;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): static
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(?string $rue): static
    {
        $this->rue = $rue;

        return $this;
    }
}

src/Form/LieuType.php
<?php

namespace App\Form;

use App\Entity\Lieu;
use App\Entity\Ville;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LieuType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder

            ->add('nom')
            ->add('rue')
            ->add('Ville', EntityType::class, [
                'class' => Ville::class,
                'choice_label' => 'nom',
            ])
            ->add('submit', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Lieu::class,
        ]);
    }
}

src/Controller/LieuController.php
<?php

namespace App\Controller;

use App\Entity\Lieu;
use App\Entity\Ville;
use App\Form\LieuType;
use App\Repository\LieuRepository;
use App\Repository\VilleRepository;
use App\Services\MapBoxHelper;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/lieu')]
class LieuController extends AbstractController
{
    #[Route('/', name: 'app_lieu_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager,LieuRepository $lieuRepository, MapBoxHelper $mapBoxHelper): Response
    {
        $hasChanged = false;
        $lieux = $lieuRepository->findAll();
        foreach ($lieux as $lieu) {
            $coordinates= $mapBoxHelper->getAddressCoordinates($lieu->getRue(), $lieu->getVille()->getCodePostal(), $lieu->getVille()->getNom());
            if(!empty($coordinates)) {
                //hydrate les coordonnées reçues dans l'entité
                $lieu->setLatitude($coordinates['lat']);
                $lieu->setLongitude($coordinates['lng']);
                $entityManager->persist($lieu);
                $hasChanged = true;
            }
        }
        if ($hasChanged)
            $entityManager->flush();
        // On évite de faire de multiple requête en BDD au max.
        return $this->render('lieu/index.html.twig', [
            'lieus' => $lieux,
        ]);
    }

    #[Route('/lieu/new', name: 'app_lieu_new', methods: ['GET', 'POST'])]
    public function new(MapBoxHelper $mapBoxHelper, Request $request, EntityManagerInterface $entityManager): Response
    {
        $lieu = new Lieu();
        $form = $this->createForm(LieuType::class, $lieu);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $ville= $form->get('Ville')->getData();
            // Définir la ville pour le lieu
            $lieu->setVille($ville);
            $rue = $form->get('rue')->getData();
            $lieu->setRue($rue);
            $coordinates= $mapBoxHelper->getAddressCoordinates($lieu->getRue(), $lieu->getVille()->getCodePostal(), $lieu->getVille()->getNom());
            if (!empty($coordinates)) {
                $lieu->setLatitude($coordinates['lat']);
                $lieu->setLongitude($coordinates['lng']);
            }
            // Enregistrer le lieu en base de données
            $entityManager->persist($lieu);
            $entityManager->flush();
            // Rediriger vers la page de détail du lieu
            $this->addFlash('success', 'Nouveau lieu ajouté avec succès !');
            return $this->redirectToRoute('app_lieu_show',['id' => $lieu->getId()]);
        }

        return $this->render('lieu/new.html.twig', [
            'lieu' => $lieu,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_lieu_show', methods: ['GET'])]
    public function show(Lieu $lieu): Response
    {
        return $this->render('lieu/show.html.twig', [
            'lieu' => $lieu,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_lieu_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Lieu $lieu, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LieuType::class, $lieu);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            $this->addFlash('success', 'Lieu modifié avec succès !');
            return $this->redirectToRoute('app_lieu_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('lieu/edit.html.twig', [
            'lieu' => $lieu,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_lieu_delete', methods: ['POST'])]
    public function delete(Request $request, Lieu $lieu, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$lieu->getId(), $request->request->get('_token'))) {
            $entityManager->remove($lieu);
            $entityManager->flush();
        }
        $this->addFlash('success', 'Lieu supprimé avec succès !');
        return $this->redirectToRoute('app_lieu_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/lieu/_delete_form.html.twig
<form method="post" action="{{ path('app_lieu_delete', {'id': lieu.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lieu.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/lieu/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Lieu{% endblock %}

{% block body %}
<div class="background-overlay"></div>
<div class="content">
    <main class="d-flex">
        <div class="container">
            {% for group, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-{{ group }}" role="alert">{{ message }}</div>
                {% endfor %}
            {% endfor %}
            <h1>Edit lieu {{ lieu.nom }}</h1>
            <div class="row">
                <div class="col-md-6">
                    {{ form_start(form) }}
                    <div class="mb-3">
                        {{ form_label(form.nom, 'Nom:', {'label_attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.nom, {'attr': {'class': 'form-control', 'readonly': 'readonly'}}) }}
                        {% set errors = form_errors(form.nom) %}
                        {% if errors %}
                            <div class="text-danger">
                                {{ errors|striptags }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.rue, 'Rue:', {'label_attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.rue, {'attr': {'class': 'form-control', 'readonly': 'readonly'}}) }}
                        {% set errors = form_errors(form.rue) %}
                        {% if errors %}
                            <div class="text-danger">
                                {{ errors|striptags }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.Ville, 'Ville:', {'label_attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.Ville, {'attr': {'class': 'form-control', 'readonly': 'readonly'}}) }}
                        {% set errors = form_errors(form.Ville) %}
                        {% if errors %}
                            <div class="text-danger">
                                {{ errors|striptags }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="d-flex justify-content-between">
                        <a href="{{ path('app_lieu_index') }}" class="btn btn-danger">Retour à la liste</a>
                        {{ form_row(form.submit, {'label': 'Modifier le lieu'}) }}
                        {{ include('lieu/_delete_form.html.twig') }}
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

templates/lieu/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lieu index{% endblock %}

{% block body %}
    <main class="d-flex">
        <div class="background-overlay"></div>
        <div class=" content container">
            {% for group, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-{{ group }}" role="alert">{{ message }}</div>
                {% endfor %}
            {% endfor %}
            <h1 class="row justify-content-center">Liste des lieux</h1>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-4">
                {% for lieu in lieus %}
                    <div class="col mb-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ lieu.nom }}</h5>
                                <p class="card-text">Rue: {{ lieu.rue }}</p>
                                <p class="card-text">Longitude: {{ lieu.longitude }}</p>
                                <p class="card-text">Latitude: {{ lieu.latitude }}</p>
                                <p class="card-text">Ville: {{ lieu.ville.nom }}</p>
                                <a href="{{ path('app_lieu_show', {'id': lieu.id}) }}"
                                   class="btn btn-primary btn-sm">show</a>
                                <a href="{{ path('app_lieu_edit', {'id': lieu.id}) }}"
                                   class="btn btn-secondary btn-sm">edit</a>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                                <p class="card-text">No records found</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <a href="{{ path('app_lieu_new') }}" class="mb-3 btn btn-success">Create Lieu</a>
        </div>
    </main>
{% endblock %}

templates/lieu/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Lieu{% endblock %}

{% block body %}
    <div class="background-overlay"></div>
    <main class="d-flex">
        <div class="content container">
            {% for group, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-{{ group }}" role="alert">{{ message }}</div>
                {% endfor %}
            {% endfor %}
            <h1 class="row justify-content-center">Create new Lieu</h1>
            <div class="row">
                <div class="col-md-6">
                    {{ form_start(form) }}
                    <div class="mb-3">
                        {{ form_label(form.nom, 'Nom:', {'label_attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
                        {% set errors = form_errors(form.nom) %}
                        {% if errors %}
                            <div class="text-danger">
                                {{ errors|striptags }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.rue, 'Rue:', {'label_attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.rue, {'attr': {'class': 'form-control'}}) }}
                        {% set errors = form_errors(form.rue) %}
                        {% if errors %}
                            <div class="text-danger">
                                {{ errors|striptags }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.Ville, 'Ville:', {'label_attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.Ville, {'attr': {'class': 'form-control'}}) }}
                        {% set errors = form_errors(form.Ville) %}
                        {% if errors %}
                            <div class="text-danger">
                                {{ errors|striptags }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="d-flex justify-content-between">
                        {{ form_row(form.submit, {'label': 'Create New', 'attr': {'class': 'btn btn-primary'}}) }}
                        <a class="btn btn-secondary" href="{{ path('app_lieu_index') }}">back to list</a>
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/lieu/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lieu{% endblock %}

{% block body %}
    <div class="background-overlay"></div>
    <h1 class="row justify-content-center">Lieu: {{ lieu.nom }}</h1>
    <main class="d-flex">
        <div class="content container d-flex flex-column">
            <link rel="stylesheet"
                  href="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/css/ol.css"
                  type="text/css">
            {% for group, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-{{ group }}" role="alert">{{ message }}</div>
                {% endfor %}
            {% endfor %}

            <div class="card mb-4 mt-4">
                <table class="table">
                    <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ lieu.id }}</td>
                    </tr>
                    <tr>
                        <th>Longitude</th>
                        <td>{{ lieu.Longitude }}</td>
                    </tr>
                    <tr>
                        <th>Latitude</th>
                        <td>{{ lieu.latitude }}</td>
                    </tr>
                    <tr>
                        <th>Nom</th>
                        <td>{{ lieu.nom }}</td>
                    </tr>
                    <tr>
                        <th>Rue</th>
                        <td>{{ lieu.rue }}</td>
                    </tr>
                    <tr>
                        <th>Ville</th>
                        <td>{{ lieu.ville.nom }}</td>
                    </tr>
                    </tbody>
                </table>
                <div class="d-flex justify-content mb-4">
                    <a href="{{ path('app_lieu_index') }}" class="btn btn-primary">back to list</a>
                    <a href="{{ path('app_lieu_edit', {'id': lieu.id}) }}" class="btn btn-secondary">edit</a>
                    {{ include('lieu/_delete_form.html.twig') }}
                </div>
            </div>

        </div>
        <div  class="card mb-4 mt-4 mx-auto" style="width: 400px;">
            <div id="map" style="width: 400px; height: 300px;"></div>
        </div>
    </main>

    <script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js"></script>
    <script>
        var map = new ol.Map({
            target: 'map',
            layers: [
                new ol.layer.Tile({
                    source: new ol.source.OSM()
                })
            ],
            view: new ol.View({
                center: ol.proj.fromLonLat([{{ lieu.Longitude }}, {{ lieu.Latitude }}]),
                zoom: 15
            })
        });

        // Ajout un marquer au lieu
        var marker = new ol.Feature({
            geometry: new ol.geom.Point(ol.proj.fromLonLat([{{ lieu.Longitude }}, {{ lieu.Latitude }}])),

        });

        var vectorSource = new ol.source.Vector({
            features: [marker]
        });

        var vectorLayer = new ol.layer.Vector({
            source: vectorSource
        });

        map.addLayer(vectorLayer);


        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function (position) {
                var userMarker = new ol.Feature({
                    geometry: new ol.geom.Point(ol.proj.fromLonLat([position.coords.longitude, position.coords.latitude])),
                    name: '          ' +
                        '            ' +
                        '              ' +
                        '     VOUS ETES ICI',
                });
// personalisation du marker du lieu
                marker.setStyle(new ol.style.Style({
                    image: new ol.style.Icon(({
                        color: '#8959A8',
                        crossOrigin: 'anonymous',
                        src: 'https://openlayers.org/en/v4.6.5/examples/data/dot.png'
                    }))
                }));


                userMarker.setStyle(new ol.style.Style({
                    image: new ol.style.Icon({
                        anchor: [0.5, 1],
                        src: 'https://openlayers.org/en/v4.6.5/examples/data/icon.png',
                        scale: 1,
                    }),
                    text: new ol.style.Text({
                        text: userMarker.get('name'),
                        fill: new ol.style.Fill({
                            color: 'green',
                        }),
                        offsetY: -20,
                    }),
                }));

                vectorSource.addFeature(userMarker);

                //pour centrer par a utilistaeur
                // map.getView().setCenter(ol.proj.fromLonLat([position.coords.longitude, position.coords.latitude]));
            });
        } else {
            alert("La géolocalisation n'est pas prise en charge par votre navigateur.");
        }
    </script>

{% endblock %}